import type { Metadata } from "next";
import "./globals.css";
import './neumorphic.css';
import { ReactNode } from "react";
import ThemeApplier from "@/components/theme/ThemeApplier";
import StyledJsxRegistry from "@/app/registry";
import ContextProvider from "@/app/contextProvider";


export const metadata: Metadata = {
    title: "Time to Work",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="en">
        <ContextProvider>
            <body>
            <ThemeApplier>
                <StyledJsxRegistry>
                    <div
                        className={`
                            flex flex-col min-h-screen
                            antialiased
                            bg-neumorphic-100 dark:bg-neumorphic-750 
                            text-neumorphic-700 dark:text-neumorphic-150 
                            stroke-neumorphic-700 dark:stroke-neumorphic-150
                        `}
                    >
                        <div className={'flex-1 flex flex-col'}>
                            {children}
                        </div>
                        <div>footer</div>
                        {/* TODO: create footer */}
                    </div>
                </StyledJsxRegistry>
            </ThemeApplier>
            </body>
        </ContextProvider>
        </html>
    );
}
