import type { Metadata } from "next";
import "./globals.css";
import './neumorphic.css';
import React from "react";
import ThemeProvider from "@/contexts/ThemeContext";
import ThemeApplier from "@/components/theme/ThemeApplier";
import StyledJsxRegistry from "@/app/registry";


export const metadata: Metadata = {
    title: "Time to Work",
    description: "Generated by create next app",
};

export default function RootLayout(
    { children }: Readonly<{ children: React.ReactNode }>
) {
    return (
        <html lang="en">
        <ThemeProvider>
            <body>
            <StyledJsxRegistry>
                <ThemeApplier>
                    <div className={'antialiased h-screen'}>
                        {children}
                    </div>
                </ThemeApplier>
            </StyledJsxRegistry>
            </body>
        </ThemeProvider>
        </html>
    );
}
